version: "3.8" 
services: 
  web: 
    build: web 
    image: gnschenker/ch11-web:1.0 
    ports: 
    - 80:3000 
  
  db: 
    build: db 
    image: gnschenker/ch11-db:1.0 
    ports: 
    - 5432:5432 
    volumes: 
    - pets-data:/var/lib/postgresql/data 

volumes: 
  pets-data: