apiVersion: v1 
kind: Pod 
metadata: 
  name: nginx 
  lables:
    app: nginx
spec: 
  containers: 
  - name: nginx 
    image: nginx:alpine 
    ports: 
    - containerPort: 80 
      name: http-web-svc 
